# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OPmyEthkeNXwY1HAng0tbBd9OoYdoRL3
"""

Data Types:

1 What are primitive data types in programming, and give examples?
2 Explain the difference between int and float data types.
3 What is type casting, and why is it important when working with data types?
4 How do you declare and use a string data type in your programming language of choice?

Operators:

5 What is the difference between the '==' and '===' operators in JavaScript?
6 Explain the concept of operator precedence and associativity.
7 How do you use the '&&' and '||' logical operators to create compound conditions?
8 What is the ternary operator, and how does it work in conditional expressions?

Conditional Statements:

9 Describe the purpose of an "if" statement and provide an example.
10 What is the difference between "if," "else if," and "else" statements in control flow?
11 Explain the concept of a switch statement and when it is preferable over a series of "if" statements.
12 What is a conditional operator (often referred to as the ternary operator), and how is it used in conditional expressions?

Looping Statements:

13 How does a "for" loop differ from a "while" loop, and when would you choose one over the other?
14 What is an infinite loop, and how can you avoid creating one in your code?
15 Explain the purpose of a "break" statement in a loop, and provide an example.
16 How can you achieve the same functionality as a "for" loop using a "foreach" loop in languages like Python or JavaScript?

Functions:

17 What is a function, and why is it useful in programming?
18 Describe the difference between function parameters and arguments.
19 What is the concept of function recursion, and when might you use it in your code?
20 Explain the difference between function declarations and function expressions in JavaScript.